### 정부호와 준정부호

- 양의 정부호(positive definite): 영 벡터가 아닌 모든 벡터 x에 대해 다음 부등식이 성립하면 행렬 A는 정부호

- 만약 이 식이 등호를 포함한다면 양의 준정부호(positive semi-definite)


### 행렬 놈

In [2]:
# 넘파이에서는 linalg 서브패키지의 norm() 명렬으로 행렬의 놈을 계산할 수 있다.
import numpy as np

In [6]:
A = (np.arange(9) - 4).reshape((3, 3))
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [7]:
np.linalg.norm(A)

7.745966692414834

### 대각합

In [8]:
np.trace(np.eye(3))

3.0

### 행렬식

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

In [3]:
X = np.array([[-2, -1, 0],
             [-1, 2, -1],
             [0, -1, 2]])
np.linalg.det(X)

-8.000000000000002

### 역행렬

In [10]:
import numpy as np

In [11]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [13]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

#### 역행렬과 선형 연립방적식의해

In [14]:
b = np.array([[2], [2], [3]])

In [15]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [17]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

#lstsq()
- A와 B를 모두 인수로 받고,
- x: 최소자승문제(least square problem)
- resid: 잔차제곱합(residual sum of squares)
- rank: 랭크
- s: 특이값
    


In [20]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\shine\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.],
       [1.],
       [1.]])

#### 선형 연립방정식과 선형 예측모형

In [21]:
#### 연습문제 2.4.5

In [22]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target



In [25]:
A = X[:4, [0, 4, 5, 6]]  #'CRIM', 'NOX', 'RM', 'AGE'
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [27]:
b = y[:4]
b

array([24. , 21.6, 34.7, 33.4])

In [28]:
#y = wX
#yX-1 = w
Aniv = np.linalg.inv(A)
Aniv

array([[-2.35172493e+01,  4.95752613e+01, -9.28388535e+01,
         7.19277399e+01],
       [ 5.96138349e+00,  6.66097478e+00, -2.68388003e+01,
         1.58431788e+01],
       [-2.19803095e-01, -8.06127089e-01,  1.99308607e+00,
        -9.57270077e-01],
       [-9.40782133e-03,  2.15240112e-02,  2.94704793e-02,
        -4.11681401e-02]])

In [29]:
x = np.dot(Aniv, b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


### 최소자승문제

In [7]:
import numpy as np

#### 역행렬 이용해서 풀기 


In [8]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [9]:
b =np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [10]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [11]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [12]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

#### lstsq() 명렬으로 풀기

In [13]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\shine\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [14]:
#resid는 잔차벡터의 e=Ax-b의 제곱합, 즉 놈의 제곱
resid, np.linalg.norm(A @ x - b)**2

(array([0.00166667]), 0.0016666666666666698)

In [15]:
#### 연습 문제 2.4.6

In [16]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [17]:
x, resid, rank, s =np.linalg.lstsq(X, y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


C:\Users\shine\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.
